import { useMemo, useState } from "react";
import { generateId } from "../lib/utils";
import type { Reflection, ReflectionCategory, ReflectionDate } from "../types/index";
import { MarkdownRenderer } from "./MarkdownRenderer";

interface Props {
  reflections: Reflection[];
  categories: ReflectionCategory[];
  onSave: (reflections: Reflection[], categories: ReflectionCategory[]) => Promise<void>;
}

const palette = ["#fbe6dc", "#fce7d7", "#eee5fb", "#dff1ee", "#e6edfb"];
const formatDate = (date: ReflectionDate) => date.precision === "unknown" ? "Date unknown" : date.precision === "year" ? String(date.year) : date.precision === "month" ? new Date(date.year, date.month - 1).toLocaleDateString(undefined, { month: "long", year: "numeric" }) : new Date(date.year, date.month - 1, date.day).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
const timelineLabel = (date: ReflectionDate) => date.precision === "unknown" ? "Date unknown" : date.precision === "year" ? String(date.year) : new Date(date.year, date.month - 1).toLocaleDateString(undefined, { month: "long", year: "numeric" });
const dateRank = (date: ReflectionDate) => date.precision === "unknown" ? -1 : date.year * 100 + (date.precision === "year" ? 0 : date.month);

export function ReflectionsView({ reflections, categories, onSave }: Props) {
  const ordered = useMemo(() => [...categories].sort((a, b) => a.order - b.order), [categories]);
  const [categoryName, setCategoryName] = useState("");
  const [editingCategory, setEditingCategory] = useState<string | null>(null);
  const [categoryValue, setCategoryValue] = useState("");
  const [editing, setEditing] = useState<Reflection | null>(null);
  const [editorOpen, setEditorOpen] = useState(false);
  const [viewing, setViewing] = useState<Reflection | null>(null);
  const now = new Date();
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [tags, setTags] = useState(""); const [categoryId, setCategoryId] = useState("");
  const [precision, setPrecision] = useState<ReflectionDate["precision"]>("day"); const [year, setYear] = useState(String(now.getFullYear())); const [month, setMonth] = useState(String(now.getMonth() + 1)); const [day, setDay] = useState(String(now.getDate()));
  const openEditor = (entry?: Reflection) => { const date = entry?.date; setEditing(entry ?? null); setTitle(entry?.title ?? ""); setContent(entry?.content ?? ""); setTags(entry?.tags.join(", ") ?? ""); setCategoryId(entry?.categoryId ?? ""); setPrecision(date?.precision ?? "day"); setYear(date && date.precision !== "unknown" ? String(date.year) : String(now.getFullYear())); setMonth(date && (date.precision === "day" || date.precision === "month") ? String(date.month) : String(now.getMonth() + 1)); setDay(date?.precision === "day" ? String(date.day) : String(now.getDate())); setEditorOpen(true); };
  const closeEditor = () => { setEditorOpen(false); setEditing(null); };
  const saveEntry = async () => { const y = Number(year), m = Number(month), d = Number(day); if (!title.trim() || (precision !== "unknown" && (!Number.isInteger(y) || y < 1 || (precision !== "year" && (!Number.isInteger(m) || m < 1 || m > 12)) || (precision === "day" && (!Number.isInteger(d) || d < 1 || d > 31))))) return; const date: ReflectionDate = precision === "unknown" ? { precision } : precision === "year" ? { precision, year: y } : precision === "month" ? { precision, year: y, month: m } : { precision, year: y, month: m, day: d }; const entry: Reflection = { id: editing?.id ?? generateId("reflection"), categoryId: categoryId || undefined, title: title.trim(), content: content.trim(), tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean), date, createdAt: editing?.createdAt ?? Date.now(), updatedAt: Date.now() }; await onSave(editing ? reflections.map((item) => item.id === entry.id ? entry : item) : [...reflections, entry], categories); closeEditor(); };
  const addCategory = async () => { const name = categoryName.trim(); if (!name) return; await onSave(reflections, [...categories, { id: generateId("reflection-category"), name, icon: "folder", color: palette[categories.length % palette.length], order: categories.length }]); setCategoryName(""); };
  const renameCategory = async (id: string) => { if (!categoryValue.trim()) return; await onSave(reflections, categories.map((category) => category.id === id ? { ...category, name: categoryValue.trim() } : category)); setEditingCategory(null); };
  const deleteCategory = async (id: string) => { if (!window.confirm("Delete this space? Its reflections will move to Unsorted.")) return; await onSave(reflections.map((entry) => entry.categoryId === id ? { ...entry, categoryId: undefined, updatedAt: Date.now() } : entry), categories.filter((category) => category.id !== id)); };
  const deleteEntry = async (entry: Reflection) => { if (!window.confirm("Delete this reflection? This cannot be undone.")) return; await onSave(reflections.filter((item) => item.id !== entry.id), categories); setViewing(null); };
  const sections = [...ordered.map((category) => ({ id: category.id, name: category.name, entries: reflections.filter((entry) => entry.categoryId === category.id) })), { id: "", name: "Unsorted", entries: reflections.filter((entry) => !entry.categoryId) }];
  return <div className="reflections-view">
    <div className="reflections-heading"><div><h2 style={{ margin: 0 }}>Reflections</h2><p className="muted" style={{ margin: "4px 0 0" }}>Keep moments, memories, and gratitude close.</p></div><button type="button" className="button button-primary" onClick={() => openEditor()}>+ Add reflection</button></div>
    <section className="reflection-manager"><strong>Spaces</strong><div className="todo-add-row" style={{ marginTop: 10 }}><input className="add-task-input" placeholder="New space name…" value={categoryName} onChange={(event) => setCategoryName(event.target.value)} onKeyDown={(event) => event.key === "Enter" && void addCategory()} /><button type="button" className="button button-secondary" onClick={() => void addCategory()}>Add space</button></div><div className="reflection-spaces">{ordered.map((category) => <div key={category.id} className="reflection-space" style={{ borderLeftColor: category.color }}>{editingCategory === category.id ? <><input className="add-task-input" value={categoryValue} onChange={(event) => setCategoryValue(event.target.value)} autoFocus /><button type="button" className="button button-primary" onClick={() => void renameCategory(category.id)}>Save</button></> : <><span>{category.name}</span><button type="button" className="button button-link" onClick={() => { setEditingCategory(category.id); setCategoryValue(category.name); }}>Edit</button><button type="button" className="button button-danger" onClick={() => void deleteCategory(category.id)}>Delete</button></>}</div>)}</div></section>
    {sections.map((section) => { const grouped = Object.values(section.entries.reduce<Record<string, Reflection[]>>((result, entry) => { const key = timelineLabel(entry.date); (result[key] ??= []).push(entry); return result; }, {})).sort((a, b) => dateRank(b[0].date) - dateRank(a[0].date)); return <details key={section.id || "unsorted"} className="group-accordion" open={section.entries.length > 0} style={{ marginBottom: 10 }}><summary className="group-accordion-summary"><span className="group-accordion-chevron" aria-hidden="true" /><span className="group-accordion-name">{section.name}</span><span className="group-progress-badge">{section.entries.length}</span></summary><div className="group-task-list">{grouped.length === 0 ? <p className="muted">No reflections here yet.</p> : grouped.map((group) => <div key={timelineLabel(group[0].date)}><h3 className="reflection-period">{timelineLabel(group[0].date)}</h3>{group.map((entry) => <article key={entry.id} className="reflection-entry"><button type="button" className="reflection-open" onClick={() => setViewing(entry)}><span className="reflection-date">{formatDate(entry.date)}</span><strong>{entry.title}</strong><span className="reflection-preview">{entry.content || "No additional details."}</span></button><div className="todo-actions"><button type="button" className="button button-secondary" onClick={() => openEditor(entry)}>Edit / move</button><button type="button" className="button button-danger" onClick={() => void deleteEntry(entry)}>Delete</button></div></article>)}</div>)}</div></details>; })}
    {editorOpen && <div className="reflection-modal-backdrop"><section className="reflection-modal" role="dialog" aria-modal="true"><header><h2>{editing ? "Edit reflection" : "New reflection"}</h2><button type="button" className="button button-link" onClick={closeEditor}>×</button></header><label>Space<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Unsorted</option>{ordered.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Title<input className="add-task-input" value={title} onChange={(event) => setTitle(event.target.value)} autoFocus /></label><label>Your reflection <span className="muted">(Markdown supported)</span><textarea className="reflection-editor" value={content} onChange={(event) => setContent(event.target.value)} /></label><label>Tags <span className="muted">(comma separated)</span><input className="add-task-input" value={tags} onChange={(event) => setTags(event.target.value)} /></label><label>Date precision<select value={precision} onChange={(event) => setPrecision(event.target.value as ReflectionDate["precision"])}><option value="day">Exact day</option><option value="month">Month and year</option><option value="year">Year only</option><option value="unknown">Date unknown</option></select></label>{precision !== "unknown" && <div className="todo-add-row"><input className="add-task-input" value={year} onChange={(event) => setYear(event.target.value)} placeholder="Year" />{precision !== "year" && <input className="add-task-input" value={month} onChange={(event) => setMonth(event.target.value)} placeholder="Month" />}{precision === "day" && <input className="add-task-input" value={day} onChange={(event) => setDay(event.target.value)} placeholder="Day" />}</div>}<footer><button type="button" className="button button-secondary" onClick={closeEditor}>Cancel</button><button type="button" className="button button-primary" onClick={() => void saveEntry()}>Save reflection</button></footer></section></div>}
    {viewing && <div className="reflection-modal-backdrop"><section className="reflection-modal reflection-reader" role="dialog" aria-modal="true"><header><h2>Reflection</h2><button type="button" className="button button-link" onClick={() => setViewing(null)}>×</button></header><span className="reflection-date">{formatDate(viewing.date)}</span>{viewing.tags.length > 0 && <div className="reflection-tags">{viewing.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div>}<h1>{viewing.title}</h1><div className="reflection-reader-content">{viewing.content ? <MarkdownRenderer content={viewing.content} /> : <p className="muted">No additional details.</p>}</div></section></div>}
  </div>;
}
